baseURL = 'https://notes-2134.vercel.app/'
languageCode = 'en-us'
title = 'My Notes'
theme = 'papermod'

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[params]
  description = "Published notes from Trilium"
